[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.build]
cmds = ["npm ci", "npm run build", "cp -r .next/static .next/standalone/.next/static", "cp -r public .next/standalone/public"]

[start]
cmd = "PORT=${PORT:-3000} HOSTNAME=0.0.0.0 node .next/standalone/server.js"
